=== JJJS888/xml_colegio/colegio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <!-- Elemento raÃ­z -->
  <xs:element name="colegios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="colegio" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="direccion" type="xs:string"/>
              <xs:element name="telefono" type="xs:string"/>

              <xs:element name="alumnos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="alumno" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre" type="xs:string"/>
                          <xs:element name="apellidos" type="xs:string"/>
                          <xs:element name="curso" type="xs:string"/>
                          <xs:element name="notaMedia" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="num_exp" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="profesores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="profesor" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre" type="xs:string"/>
                          <xs:element name="apellidos" type="xs:string"/>
                          <xs:element name="asignatura" type="xs:string"/>
                          <xs:element name="telefono" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="asignaturas">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="asignatura" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre" type="xs:string"/>
                          <xs:element name="codigo" type="xs:string"/>
                          <xs:element name="creditos" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
            <xs:attribute name="codigo" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JJJS888/xml_colegio/colegio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="colegio.xsl"?>
<colegios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="colegio.xsd">

    <colegio codigo="C001">
        <nombre>Marpe</nombre>
        <direccion>Altavista</direccion>
        <telefono>928.35.12.21</telefono>
   

    <alumnos>
        <alumno num_exp="A001">
            <nombre></nombre>
            <apellidos></apellidos>
            <curso></curso>
            <notaMedia></notaMedia>
        </alumno>
    </alumnos>

    <profesores>
       <profesor codigo="P001">
            <nombre></nombre>
            <apellidos></apellidos>
            <asignatura></asignatura>
            <telefono></telefono>
        </profesor>
    </profesores>

    <asignaturas>
        <asignatura codigo="MATH101">
            <nombre></nombre>
            <codigo></codigo>
            <creditos></creditos>
        </asignatura>
    </asignaturas>

     </colegio>

</colegios>
